DebtCalculatorWebApp/Controllers/AutoLoansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DebtCalculatorWebApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace DebtCalculatorWebApp.Controllers
{
    [Authorize]
    public class AutoLoansController : Controller
    {
        private readonly DebtCalculatorWebAppContext _context;

        public AutoLoansController(DebtCalculatorWebAppContext context)
        {
            _context = context;
        }

        // GET: AutoLoans
        public async Task<IActionResult> Index()
        {
            return View(await _context.AutoLoan.ToListAsync());
        }

        // GET: AutoLoans/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autoLoan = await _context.AutoLoan
                .FirstOrDefaultAsync(m => m.AutoLoanId == id);
            if (autoLoan == null)
            {
                return NotFound();
            }

            return View(autoLoan);
        }

        // GET: AutoLoans/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AutoLoans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AutoLoanId,AutoLoanAmount,AutoLoanTime,AutoLoanApr,RecordDate")] AutoLoan autoLoan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(autoLoan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(autoLoan);
        }

        // GET: AutoLoans/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autoLoan = await _context.AutoLoan.FindAsync(id);
            if (autoLoan == null)
            {
                return NotFound();
            }
            return View(autoLoan);
        }

        // POST: AutoLoans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AutoLoanId,AutoLoanAmount,AutoLoanTime,AutoLoanApr,RecordDate")] AutoLoan autoLoan)
        {
            if (id != autoLoan.AutoLoanId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(autoLoan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AutoLoanExists(autoLoan.AutoLoanId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(autoLoan);
        }

        // GET: AutoLoans/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autoLoan = await _context.AutoLoan
                .FirstOrDefaultAsync(m => m.AutoLoanId == id);
            if (autoLoan == null)
            {
                return NotFound();
            }

            return View(autoLoan);
        }

        // POST: AutoLoans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var autoLoan = await _context.AutoLoan.FindAsync(id);
            _context.AutoLoan.Remove(autoLoan);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AutoLoanExists(int id)
        {
            return _context.AutoLoan.Any(e => e.AutoLoanId == id);
        }
    }
}

DebtCalculatorWebApp/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DebtCalculatorWebApp.Models;
using DebtCalculatorWebApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DebtCalculatorWebApp.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Results(AutoLoan autoLoan, CreditCardLoan creditCardLoan, Mortgage mortgage)
        {
            CalculatorCreateViewModels Vm = new CalculatorCreateViewModels()
            {
                AutoLoan = autoLoan,
                CreditCardLoan = creditCardLoan,
                Mortgage = mortgage
            };

            return View(Vm);
        }
    }
}

DebtCalculatorWebApp/Controllers/CreditCardLoansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DebtCalculatorWebApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace DebtCalculatorWebApp.Controllers
{
    [Authorize]
    public class CreditCardLoansController : Controller
    {
        private readonly DebtCalculatorWebAppContext _context;

        public CreditCardLoansController(DebtCalculatorWebAppContext context)
        {
            _context = context;
        }

        // GET: CreditCardLoans
        public async Task<IActionResult> Index()
        {
            return View(await _context.CreditCardLoan.ToListAsync());
        }

        // GET: CreditCardLoans/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var creditCardLoan = await _context.CreditCardLoan
                .FirstOrDefaultAsync(m => m.CreditCardLoanId == id);
            if (creditCardLoan == null)
            {
                return NotFound();
            }

            return View(creditCardLoan);
        }

        // GET: CreditCardLoans/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CreditCardLoans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CreditCardLoanId,CreditCardLoanAmount,CreditCardLoanTime,CreditcardLoanApr,RecordDate")] CreditCardLoan creditCardLoan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(creditCardLoan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(creditCardLoan);
        }

        // GET: CreditCardLoans/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var creditCardLoan = await _context.CreditCardLoan.FindAsync(id);
            if (creditCardLoan == null)
            {
                return NotFound();
            }
            return View(creditCardLoan);
        }

        // POST: CreditCardLoans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CreditCardLoanId,CreditCardLoanAmount,CreditCardLoanTime,CreditcardLoanApr,RecordDate")] CreditCardLoan creditCardLoan)
        {
            if (id != creditCardLoan.CreditCardLoanId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(creditCardLoan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CreditCardLoanExists(creditCardLoan.CreditCardLoanId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(creditCardLoan);
        }

        // GET: CreditCardLoans/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var creditCardLoan = await _context.CreditCardLoan
                .FirstOrDefaultAsync(m => m.CreditCardLoanId == id);
            if (creditCardLoan == null)
            {
                return NotFound();
            }

            return View(creditCardLoan);
        }

        // POST: CreditCardLoans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var creditCardLoan = await _context.CreditCardLoan.FindAsync(id);
            _context.CreditCardLoan.Remove(creditCardLoan);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CreditCardLoanExists(int id)
        {
            return _context.CreditCardLoan.Any(e => e.CreditCardLoanId == id);
        }
    }
}

DebtCalculatorWebApp/Controllers/MortgagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DebtCalculatorWebApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace DebtCalculatorWebApp.Controllers
{
    [Authorize]
    public class MortgagesController : Controller
    {
        private readonly DebtCalculatorWebAppContext _context;

        public MortgagesController(DebtCalculatorWebAppContext context)
        {
            _context = context;
        }

        // GET: Mortgages
        public async Task<IActionResult> Index()
        {
            return View(await _context.Mortgage.ToListAsync());
        }

        // GET: Mortgages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mortgage = await _context.Mortgage
                .FirstOrDefaultAsync(m => m.MortgageId == id);
            if (mortgage == null)
            {
                return NotFound();
            }

            return View(mortgage);
        }

        // GET: Mortgages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Mortgages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MortgageId,MortgageAmount,MortgageTime,MortgageApr,RecordDate")] Mortgage mortgage)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mortgage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mortgage);
        }

        // GET: Mortgages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mortgage = await _context.Mortgage.FindAsync(id);
            if (mortgage == null)
            {
                return NotFound();
            }
            return View(mortgage);
        }

        // POST: Mortgages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MortgageId,MortgageAmount,MortgageTime,MortgageApr,RecordDate")] Mortgage mortgage)
        {
            if (id != mortgage.MortgageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mortgage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MortgageExists(mortgage.MortgageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mortgage);
        }

        // GET: Mortgages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mortgage = await _context.Mortgage
                .FirstOrDefaultAsync(m => m.MortgageId == id);
            if (mortgage == null)
            {
                return NotFound();
            }

            return View(mortgage);
        }

        // POST: Mortgages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mortgage = await _context.Mortgage.FindAsync(id);
            _context.Mortgage.Remove(mortgage);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MortgageExists(int id)
        {
            return _context.Mortgage.Any(e => e.MortgageId == id);
        }
    }
}

DebtCalculatorWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DebtCalculator Web App</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color: darkslategray;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Calculator" asp-action="Create">Debt Calculator</a></li>
                </ul>
                
            </div>
        </div>
    </nav>
    <div style="width:170px; height:600px; border:solid; background-color:darkslategray; float:left;">
        <ul class="nav flex-column">
            <li class="nav-item"><a asp-controller="AutoLoans" asp-action="Create">Automobile Loan</a></li>
            <li class="nav-item"><a asp-controller="CreditCardLoans" asp-action="Create">Credit Card Loan</a></li>
            <li class="nav-item"><a asp-controller="Mortgages" asp-action="Create">Mortgage</a></li>
            <li class="nav-item"><a asp-controller="LoginCalculator" asp-action="LoginResults">Loan History</a></li>
        </ul>
        <partial name="_LoginPartial" />
    </div>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - DebtCalculator Web App</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>